version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: samuel
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: appointments_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: mcp_api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+psycopg2://samuel:mypassword@db:5432/appointments_db"

volumes:
  postgres_data:
